apiVersion: apps/v1
kind: Deployment
metadata:
  name: userCenter
  namespace: go-zero-tutorial
  labels:
    app: userCenter
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: userCenter
  template:
    metadata:
      labels:
        app: userCenter
    spec:
      containers:
      - name: userCenter
        image: userCenterDockerImage:v1.0
        ports:
        - containerPort: 31001
        readinessProbe:
          tcpSocket:
            port: 31001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 31001
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

---

apiVersion: v1
kind: Service
metadata:
  name: userCenter-svc
  namespace: go-zero-tutorial
spec:
  ports:
  - port: 31001
    targetPort: 31001
  selector:
    app: userCenter

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: userCenter-hpa-c
  namespace: go-zero-tutorial
  labels:
    app: userCenter-hpa-c
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: userCenter
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: userCenter-hpa-m
  namespace: go-zero-tutorial
  labels:
    app: userCenter-hpa-m
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: userCenter
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80
