// Code generated by goctl. DO NOT EDIT.
package types

type SearchCartTotalRequest struct {
	Account string `form:"account"`
}

type SearchCartTotalResponse struct {
	UserId  int64  `json:"userId"`
	Account string `json:"account"` // 用户账号
	Count   int    `json:"count"`   // 当前用户账号加入购物车数量
}
