// Code generated by goctl. DO NOT EDIT.
// Source: cart.proto

package cart

import (
	"context"

	"go-zero-tutorial/service/cart/rpc/proto"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SearchUserCartTotalRequest  = proto.SearchUserCartTotalRequest
	SearchUserCartTotalResponse = proto.SearchUserCartTotalResponse

	Cart interface {
		SearchUserCartTotal(ctx context.Context, in *SearchUserCartTotalRequest, opts ...grpc.CallOption) (*SearchUserCartTotalResponse, error)
	}

	defaultCart struct {
		cli zrpc.Client
	}
)

func NewCart(cli zrpc.Client) Cart {
	return &defaultCart{
		cli: cli,
	}
}

func (m *defaultCart) SearchUserCartTotal(ctx context.Context, in *SearchUserCartTotalRequest, opts ...grpc.CallOption) (*SearchUserCartTotalResponse, error) {
	client := proto.NewCartClient(m.cli.Conn())
	return client.SearchUserCartTotal(ctx, in, opts...)
}
