// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	auth "go-zero-tutorial/service/userCenter/api/internal/handler/auth"
	"go-zero-tutorial/service/userCenter/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/userLists",
				Handler: auth.UserHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthUserMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/me",
					Handler: auth.MeHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1/auth"),
	)
}
