// Code generated by goctl. DO NOT EDIT.
// Source: cart.proto

package server

import (
	"context"

	"go-zero-tutorial/service/cart/rpc/cartRpc/internal/logic"
	"go-zero-tutorial/service/cart/rpc/cartRpc/internal/svc"
	"go-zero-tutorial/service/cart/rpc/cartRpc/proto"
)

type CartServer struct {
	svcCtx *svc.ServiceContext
	proto.UnimplementedCartServer
}

func NewCartServer(svcCtx *svc.ServiceContext) *CartServer {
	return &CartServer{
		svcCtx: svcCtx,
	}
}

func (s *CartServer) SearchUserCartTotal(ctx context.Context, in *proto.SearchUserCartTotalRequest) (*proto.SearchUserCartTotalResponse, error) {
	l := logic.NewSearchUserCartTotalLogic(ctx, s.svcCtx)
	return l.SearchUserCartTotal(in)
}
