// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"go-zero-tutorial/service/cart/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/carts/:userId/total",
				Handler: searchCartTotalHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/carts/total",
				Handler: cartTotalHandler(serverCtx),
			},
		},
	)
}
